source: site

paths:
  uploads: images
  static: ""

commit_templates:
  - label: Default message
    template_string: '[default_commit_message]'
  - label: Custom message
    template_string: '{message}'

collections_config:
  pages:
    icon: feed
    path: pages
    url: "/[slug]/"
    disable_add_folder: true
    schemas:
      default:
        path: .cloudcannon/schemas/page.html
    _enabled_editors:
      - visual
  blog:
    icon: article
    path: blog
    url: "/blog/[slug]/"
    disable_add_folder: true
    schemas:
      default:
        path: .cloudcannon/schemas/post.md
    preview:
      metadata: 
        - icon: newspaper
          text: 
            - key: tags
    _enabled_editors:
      - content
      - visual
    _inputs:
      title:
        type: text
        options:
          required: true
      post_permalink:
        hidden: true
      featuredImg.image:
        type: image
        comment: The hero image used at the top of the page
        options:
          width: 1296
          resize_style: crop
      thumbImg.image:
        type: image
        options:
          required: true
          width: 500
          height: 413
          resize_style: crop
  data: 
    icon: settings
    path: _data
    disable_url: true
    disable_add: true
    disable_add_folder: true
    _enabled_editors:
      - data
    glob:
      - "!nav.json"
      - "!footer.json"
      - "!theme.json"
  site_navigation:
    icon: table_rows
    path: _data
    disable_url: true
    disable_add: true
    disable_add_folder: true
    _enabled_editors:
      - data
    glob:
      - nav.json
      - footer.json
    _inputs:
      social:
        options:
          structures: _structures.social 
          preview:
            icon: link
      sections:
        options:
          structures: _structures.sections
          preview:
            icon: link
      nav_items:
        options:
          structures: _structures.nav_items
      enable_nav_btn:
        type: switch
      nav_btn:
        hidden: "!enable_nav_btn"
  theme_palette:
    icon: palette
    path: _data
    disable_url: true
    disable_add: true
    disable_add_folder: true
    _enabled_editors:
      - data
    glob:
      - theme.json

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blogging
    collections:
      - blog
  - heading: Site Settings
    collections:
      - data
      - theme_palette
      - site_navigation

data_config:
  blog-tags:
    path: _data/blog-tags.json

_inputs:
  permalink:
    type: text
    options:
      pattern: '^[\/].*[\/]$|^\/$'
      pattern_message: Permalink must start and end with a forward slash.
  image:
    type: image
    options:
      max_file_size: 5000
      max_file_size_message: For page performance, keep images under 5MB. Before uploading, consider processing your image to be a smaller size, or lower quality. If needed, this maximum can be configured in your cloudcannon.config.yml file.
  layout:
    hidden: true
  eleventyExcludeFromCollections:
    hidden: true
  seo:
    type: object
    comment: Set SEO values for the page. [Site defaults](cloudcannon:collections/data/site.json) will be used if values are not set on the page
    options:
      preview:
        icon: query_stats
        text:
          - 'Search engine optimization'
        subtext:
          - key: page_description
          - 'Update SEO values for the page'
  date:
    instance_value: NOW
  title_suffix:
    comment: Added at the end of the title and highlighted in a different color
  pagination.data:
    hidden: true
  pagination.alias:
    hidden: true
  pagination.size:
    type: number
  links:
    options:
      structures: _structures.links
  features:
    options:
      structures: _structures.features
  logo_url:
    comment: Link for the logo in the top left of the footer
  copyright:
    comment: Automatically prefixed with the current year
  page_description:
    comment: If empty, defaults to the description set in the Site SEO data file 
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
  favicon_image:
    type: image
    comment: For the icon meta tag
  canonical_url:
    comment: If empty, defaults to the page URL
  seo.featured_image:
    comment: Defaults to the image set in the Site SEO data file
  open_graph_type:
    type: select
    options:
      values: 
        - website
        - article
        - profile
  author_twitter_handle:
    type: twitter
    comment: Defaults to the twitter site value set in the Site SEO data file
  no_index:
    type: checkbox
    comment: When selected this removes the page from your sitemap and adds the noindex robots meta tag
  logo:
    type: image
  tags:
    type: multiselect
    options: 
      values: data.blog-tags
  twitter_site:
    type: twitter
    label: Twitter Username

_structures:
  features:
    values:
      - value:
          item:
          active_feature:
        _inputs:
          active_feature:
            type: switch
  social:
    values:
      - value:
          link: 
          icon: 
          icon_alt:
        preview:
          icon: diversity_1
          text:
            - key: icon_alt
            - Social Link
          subtext: 
            - key: link
            - Update Social Link details
        _inputs:
          icon:
            type: select
            options:
              values:
                - name: Facebook
                  value: ph-facebook-logo
                - name: Instagram
                  value: ph-instagram-logo
                - name: Twitter
                  value: ph-twitter-logo
                - name: Github
                  value: ph-github-logo
                - name: Youtube
                  value: ph-youtube-logo
              value_key: value
              preview:
                text:
                  - key: name
  sections:
    values:
      - value:
          title:
          links:
        preview:
          icon: sort
  links:
    values:
      - value:
          text: 
          link:
        preview:
          icon: link
  nav_items:
    values:
      - value:
          text: 
          link:
          enable_dropdown:
          dropdown: []
        _inputs:
          enable_dropdown:
            type: switch
          dropdown:
            type: array
            options: 
              structures: _structures.dropdown
            label: Dropdown Items
            hidden: "!enable_dropdown"
        preview:
          icon: link
          text:
            - key: text
          subtext: 
            - key: link
  dropdown: 
    values:
      - value:
          dropdown_text:
          dropdown_link:
        _inputs:   
          dropdown_link:
            type: url
            label: Link
          dropdown_text:
            type: text
            label: Name
        preview:
          icon: link